// flow-typed signature: a626aff3a76538b9ea1312c9e620bde5
// flow-typed version: <<STUB>>/sequelize-cockroachdb_v^1.0.3/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sequelize-cockroachdb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sequelize-cockroachdb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sequelize-cockroachdb/tests/enum_test' {
  declare module.exports: any;
}

declare module 'sequelize-cockroachdb/tests/helper' {
  declare module.exports: any;
}

declare module 'sequelize-cockroachdb/tests/int_test' {
  declare module.exports: any;
}

declare module 'sequelize-cockroachdb/tests/upsert_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sequelize-cockroachdb/index' {
  declare module.exports: $Exports<'sequelize-cockroachdb'>;
}
declare module 'sequelize-cockroachdb/index.js' {
  declare module.exports: $Exports<'sequelize-cockroachdb'>;
}
declare module 'sequelize-cockroachdb/tests/enum_test.js' {
  declare module.exports: $Exports<'sequelize-cockroachdb/tests/enum_test'>;
}
declare module 'sequelize-cockroachdb/tests/helper.js' {
  declare module.exports: $Exports<'sequelize-cockroachdb/tests/helper'>;
}
declare module 'sequelize-cockroachdb/tests/int_test.js' {
  declare module.exports: $Exports<'sequelize-cockroachdb/tests/int_test'>;
}
declare module 'sequelize-cockroachdb/tests/upsert_test.js' {
  declare module.exports: $Exports<'sequelize-cockroachdb/tests/upsert_test'>;
}
