// flow-typed signature: 768f90933d9e5e031db85d19db1a7874
// flow-typed version: <<STUB>>/serverless-http_v^1.5.2/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serverless-http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serverless-http' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serverless-http/examples/hapi/src/index' {
  declare module.exports: any;
}

declare module 'serverless-http/examples/hapi/src/plugins' {
  declare module.exports: any;
}

declare module 'serverless-http/examples/hapi/src/routes/base' {
  declare module.exports: any;
}

declare module 'serverless-http/examples/hapi/src/server' {
  declare module.exports: any;
}

declare module 'serverless-http/lib/clean-up-event' {
  declare module.exports: any;
}

declare module 'serverless-http/lib/dispatch' {
  declare module.exports: any;
}

declare module 'serverless-http/lib/finish' {
  declare module.exports: any;
}

declare module 'serverless-http/lib/get-body' {
  declare module.exports: any;
}

declare module 'serverless-http/lib/get-handler' {
  declare module.exports: any;
}

declare module 'serverless-http/lib/get-string' {
  declare module.exports: any;
}

declare module 'serverless-http/lib/is-binary' {
  declare module.exports: any;
}

declare module 'serverless-http/lib/request' {
  declare module.exports: any;
}

declare module 'serverless-http/lib/response' {
  declare module.exports: any;
}

declare module 'serverless-http/lib/sanitize-headers' {
  declare module.exports: any;
}

declare module 'serverless-http/serverless-http' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serverless-http/examples/hapi/src/index.js' {
  declare module.exports: $Exports<'serverless-http/examples/hapi/src/index'>;
}
declare module 'serverless-http/examples/hapi/src/plugins.js' {
  declare module.exports: $Exports<'serverless-http/examples/hapi/src/plugins'>;
}
declare module 'serverless-http/examples/hapi/src/routes/base.js' {
  declare module.exports: $Exports<'serverless-http/examples/hapi/src/routes/base'>;
}
declare module 'serverless-http/examples/hapi/src/server.js' {
  declare module.exports: $Exports<'serverless-http/examples/hapi/src/server'>;
}
declare module 'serverless-http/lib/clean-up-event.js' {
  declare module.exports: $Exports<'serverless-http/lib/clean-up-event'>;
}
declare module 'serverless-http/lib/dispatch.js' {
  declare module.exports: $Exports<'serverless-http/lib/dispatch'>;
}
declare module 'serverless-http/lib/finish.js' {
  declare module.exports: $Exports<'serverless-http/lib/finish'>;
}
declare module 'serverless-http/lib/get-body.js' {
  declare module.exports: $Exports<'serverless-http/lib/get-body'>;
}
declare module 'serverless-http/lib/get-handler.js' {
  declare module.exports: $Exports<'serverless-http/lib/get-handler'>;
}
declare module 'serverless-http/lib/get-string.js' {
  declare module.exports: $Exports<'serverless-http/lib/get-string'>;
}
declare module 'serverless-http/lib/is-binary.js' {
  declare module.exports: $Exports<'serverless-http/lib/is-binary'>;
}
declare module 'serverless-http/lib/request.js' {
  declare module.exports: $Exports<'serverless-http/lib/request'>;
}
declare module 'serverless-http/lib/response.js' {
  declare module.exports: $Exports<'serverless-http/lib/response'>;
}
declare module 'serverless-http/lib/sanitize-headers.js' {
  declare module.exports: $Exports<'serverless-http/lib/sanitize-headers'>;
}
declare module 'serverless-http/serverless-http.js' {
  declare module.exports: $Exports<'serverless-http/serverless-http'>;
}
