service:
  name: blog-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2
  stage: dev
  environment:
    SECRET_KEY : ${file(./env.json):SECRET_KEY}
    COCKROACHDB_HOST: ${file(./env.json):COCKROACHDB_HOST}
    COCKROACHDB_PW: ${file(./env.json):COCKROACHDB_PW}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DetachNetworkInterface"
        - "ec2:DeleteNetworkInterface"
      Resource: "*"

functions:
  api:
    handler: src/api.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
    vpc:
      securityGroupIds:
        - sg-09a31af2f0fd82304
      subnetIds:
        - subnet-14ca7b58