service:
  name: blog-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2
  stage: dev
  environment:
    SECRET_KEY : ${file(./env.json):SECRET_KEY}
    COCKROACHDB_HOST: ${file(./env.json):COCKROACHDB_HOST}
    COCKROACHDB_PW: ${file(./env.json):COCKROACHDB_PW}
    MAILGUN_KEY:  ${file(./env.json):MAILGUN_KEY}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DetachNetworkInterface"
        - "ec2:DeleteNetworkInterface"
        - "ses:SendEmail"
      Resource: "*"

functions:
  api:
    handler: src/api.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: 'https://songc.io'
            headers:
              - Cookie
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
          cors:
            origin: 'https://songc.io'
            headers:
              - Cookie
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
    vpc:
      securityGroupIds:
        - sg-09a31af2f0fd82304
      subnetIds:
        - subnet-02171c32e8e76b95f
        - subnet-068f243977e2a5b16
        - subnet-0a570ec07c65925e4