// flow-typed signature: 95bc6177aa08f27c1b1178740888128b
// flow-typed version: <<STUB>>/babel-preset-react-app_v^7.0.2/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-react-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-react-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-react-app/create' {
  declare module.exports: any;
}

declare module 'babel-preset-react-app/dependencies' {
  declare module.exports: any;
}

declare module 'babel-preset-react-app/dev' {
  declare module.exports: any;
}

declare module 'babel-preset-react-app/prod' {
  declare module.exports: any;
}

declare module 'babel-preset-react-app/test' {
  declare module.exports: any;
}

declare module 'babel-preset-react-app/webpack-overrides' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-react-app/create.js' {
  declare module.exports: $Exports<'babel-preset-react-app/create'>;
}
declare module 'babel-preset-react-app/dependencies.js' {
  declare module.exports: $Exports<'babel-preset-react-app/dependencies'>;
}
declare module 'babel-preset-react-app/dev.js' {
  declare module.exports: $Exports<'babel-preset-react-app/dev'>;
}
declare module 'babel-preset-react-app/index' {
  declare module.exports: $Exports<'babel-preset-react-app'>;
}
declare module 'babel-preset-react-app/index.js' {
  declare module.exports: $Exports<'babel-preset-react-app'>;
}
declare module 'babel-preset-react-app/prod.js' {
  declare module.exports: $Exports<'babel-preset-react-app/prod'>;
}
declare module 'babel-preset-react-app/test.js' {
  declare module.exports: $Exports<'babel-preset-react-app/test'>;
}
declare module 'babel-preset-react-app/webpack-overrides.js' {
  declare module.exports: $Exports<'babel-preset-react-app/webpack-overrides'>;
}
