// flow-typed signature: cc0b60864a567f97811d28f32488a59b
// flow-typed version: <<STUB>>/include-media_v^1.4.9/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'include-media'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'include-media' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'include-media/eyeglass-exports' {
  declare module.exports: any;
}

declare module 'include-media/Gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'include-media/eyeglass-exports.js' {
  declare module.exports: $Exports<'include-media/eyeglass-exports'>;
}
declare module 'include-media/Gulpfile.js' {
  declare module.exports: $Exports<'include-media/Gulpfile'>;
}
declare module 'include-media/index' {
  declare module.exports: $Exports<'include-media'>;
}
declare module 'include-media/index.js' {
  declare module.exports: $Exports<'include-media'>;
}
