// flow-typed signature: b54f758157c69d9fd5eea21506ca1023
// flow-typed version: <<STUB>>/open-color_v^1.6.3/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'open-color'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'open-color' {
  declare module.exports: any;
}
