// flow-typed signature: dc1bab2f1ddac7e8b125cd93eac8fc4c
// flow-typed version: <<STUB>>/redux-pender_v^2.0.12/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-pender'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-pender' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-pender/lib/index' {
  declare module.exports: any;
}

declare module 'redux-pender/lib/middleware' {
  declare module.exports: any;
}

declare module 'redux-pender/lib/penderReducer' {
  declare module.exports: any;
}

declare module 'redux-pender/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-pender/lib/index.js' {
  declare module.exports: $Exports<'redux-pender/lib/index'>;
}
declare module 'redux-pender/lib/middleware.js' {
  declare module.exports: $Exports<'redux-pender/lib/middleware'>;
}
declare module 'redux-pender/lib/penderReducer.js' {
  declare module.exports: $Exports<'redux-pender/lib/penderReducer'>;
}
declare module 'redux-pender/lib/utils.js' {
  declare module.exports: $Exports<'redux-pender/lib/utils'>;
}
